# Generated by Django 6.0.6 on 2026-08-16 15:47

import django.db.models.deletion
from django.db import migrations, models

import catalog.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("meta_title", models.CharField(blank=True, default="", max_length=255)),
                ("meta_title_en", models.CharField(blank=True, default="", max_length=255, null=True)),
                ("meta_title_ru", models.CharField(blank=True, default="", max_length=255, null=True)),
                ("meta_description", models.CharField(blank=True, default="", max_length=500)),
                ("meta_description_en", models.CharField(blank=True, default="", max_length=500, null=True)),
                ("meta_description_ru", models.CharField(blank=True, default="", max_length=500, null=True)),
                ("seo_text", models.TextField(blank=True, default="")),
                ("seo_text_en", models.TextField(blank=True, default="", null=True)),
                ("seo_text_ru", models.TextField(blank=True, default="", null=True)),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_ru", models.CharField(max_length=255, null=True)),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, validators=[catalog.validators.validate_not_reserved]
                    ),
                ),
                ("code", models.CharField(blank=True, default="", max_length=2)),
                ("is_popular", models.BooleanField(default=False)),
                ("position", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("meta_title", models.CharField(blank=True, default="", max_length=255)),
                ("meta_title_en", models.CharField(blank=True, default="", max_length=255, null=True)),
                ("meta_title_ru", models.CharField(blank=True, default="", max_length=255, null=True)),
                ("meta_description", models.CharField(blank=True, default="", max_length=500)),
                ("meta_description_en", models.CharField(blank=True, default="", max_length=500, null=True)),
                ("meta_description_ru", models.CharField(blank=True, default="", max_length=500, null=True)),
                ("seo_text", models.TextField(blank=True, default="")),
                ("seo_text_en", models.TextField(blank=True, default="", null=True)),
                ("seo_text_ru", models.TextField(blank=True, default="", null=True)),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_ru", models.CharField(max_length=255, null=True)),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, validators=[catalog.validators.validate_not_reserved]
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Document type",
                "verbose_name_plural": "Document types",
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_ru", models.CharField(max_length=255, null=True)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("description_en", models.TextField(blank=True, default="", null=True)),
                ("description_ru", models.TextField(blank=True, default="", null=True)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("file", models.FileField(upload_to="files/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_title", models.CharField(blank=True, default="", max_length=255)),
                ("meta_title_en", models.CharField(blank=True, default="", max_length=255, null=True)),
                ("meta_title_ru", models.CharField(blank=True, default="", max_length=255, null=True)),
                ("meta_description", models.CharField(blank=True, default="", max_length=500)),
                ("meta_description_en", models.CharField(blank=True, default="", max_length=500, null=True)),
                ("meta_description_ru", models.CharField(blank=True, default="", max_length=500, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="products", to="catalog.country"
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="products", to="catalog.documenttype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-year", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="images/")),
                ("card", models.ImageField(blank=True, editable=False, upload_to="images/")),
                ("card_webp", models.ImageField(blank=True, editable=False, upload_to="images/")),
                ("page", models.ImageField(blank=True, editable=False, upload_to="images/")),
                ("page_webp", models.ImageField(blank=True, editable=False, upload_to="images/")),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="catalog.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product image",
                "verbose_name_plural": "Product images",
                "ordering": ["position", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_active", "country", "document_type"], name="catalog_pro_is_acti_46e350_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["year"], name="catalog_pro_year_757c12_idx"),
        ),
    ]
