# Generated by Django 6.0.6 on 2026-08-22 20:48

from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="file",
            field=models.FileField(storage=catalog.models.product_file_storage, upload_to=""),
        ),
    ]
