# Generated by Django 6.0.6 on 2026-09-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_product_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": [
                    models.OrderBy(models.F("year"), descending=True, nulls_last=True),
                    "name",
                    "pk",
                ],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
