# Generated by Django 6.0.6 on 2026-08-16 15:47

from django.db import migrations, models

import backend.urlspace


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, validators=[backend.urlspace.validate_not_reserved]),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_ru", models.CharField(max_length=255, null=True)),
                ("body", models.TextField(blank=True, default="")),
                ("body_en", models.TextField(blank=True, default="", null=True)),
                ("body_ru", models.TextField(blank=True, default="", null=True)),
                ("meta_title", models.CharField(blank=True, default="", max_length=255)),
                ("meta_title_en", models.CharField(blank=True, default="", max_length=255, null=True)),
                ("meta_title_ru", models.CharField(blank=True, default="", max_length=255, null=True)),
                ("meta_description", models.CharField(blank=True, default="", max_length=500)),
                ("meta_description_en", models.CharField(blank=True, default="", max_length=500, null=True)),
                ("meta_description_ru", models.CharField(blank=True, default="", max_length=500, null=True)),
                ("is_published", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("support_url", models.CharField(blank=True, default="", max_length=500)),
                ("contact_email", models.EmailField(blank=True, default="", max_length=254)),
                ("footer_note", models.TextField(blank=True, default="")),
                ("footer_note_en", models.TextField(blank=True, default="", null=True)),
                ("footer_note_ru", models.TextField(blank=True, default="", null=True)),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(blank=True, upload_to="slides/")),
                ("title", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_ru", models.CharField(max_length=255, null=True)),
                ("text", models.TextField(blank=True, default="")),
                ("text_en", models.TextField(blank=True, default="", null=True)),
                ("text_ru", models.TextField(blank=True, default="", null=True)),
                ("button_label", models.CharField(blank=True, default="", max_length=255)),
                ("button_label_en", models.CharField(blank=True, default="", max_length=255, null=True)),
                ("button_label_ru", models.CharField(blank=True, default="", max_length=255, null=True)),
                ("button_url", models.CharField(blank=True, default="", max_length=500)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Slide",
                "verbose_name_plural": "Slides",
                "ordering": ["position", "pk"],
            },
        ),
    ]
