# Generated by Django 6.0.6 on 2026-08-16 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=255)),
                ("subject_en", models.CharField(max_length=255, null=True)),
                ("subject_ru", models.CharField(max_length=255, null=True)),
                ("body", models.TextField(help_text="HTML email body")),
                ("body_en", models.TextField(help_text="HTML email body", null=True)),
                ("body_ru", models.TextField(help_text="HTML email body", null=True)),
                (
                    "test_email",
                    models.EmailField(blank=True, help_text="Address for the 'Send test email' action", max_length=254),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("QUEUED", "Queued"),
                            ("SENDING", "Sending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Broadcast",
                "verbose_name_plural": "Broadcasts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BroadcastDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "state",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("SENT", "Sent"), ("FAILED", "Failed")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="mailing.broadcast"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_deliveries",
                        to="customer.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Broadcast delivery",
                "verbose_name_plural": "Broadcast deliveries",
                "ordering": ["broadcast", "customer"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("broadcast", "customer"), name="one_delivery_per_broadcast_customer"
                    )
                ],
            },
        ),
    ]
